### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by DonRichards** [vjeantet/alerter#10]
Sorry, I know this will seem insanely simple but would it be possible to add a tiny install section? 
```markdown
...
[Download](...#)
Prebuilt binaries are available from the releases section.

# Installation 
...
# Usage
..
```

**Comment by julienXX** [comment]
Would you like to submit a pull request for the documentation or some basics?

**Comment by DonRichards** [comment]
I'd love to but I have no clue what these would need. In fact I'm not even sure how to install myself.

**Comment by masukomi** [comment]
@DonRichards 

1. download the precompiled binary
2. extract it

then `echo $PATH` 
that's a list of directories where you can put it and have it be accessible from anywhere. 

`cp ~/Downloads/alerter /path/to/directory/you/chose/`
