### ISSUE TITLE
10.15 Catalina Support?

### ISSUE THREAD

**Issue by MAJ007** [vjeantet/alerter#22]
Love the app like so many. Any chance you can make it supportable in 10.15?
Doesn't work on latest beta build 19A558d

**Comment by pavstor** [comment]
Same here. Would be great to get Catalina support!

**Comment by kkoomen** [comment]
Same here.

**Comment by mhvuze** [comment]
I just came across this tool, running 10.15.1. Is it expected (mis)behavior that alerter can be opened and shows the parameters etc. but doesn't actually run/gets stuck when trying to run one of the samples or my own?

**Comment by Zmaon** [comment]
Same here, I'm using alerter in an app and it stopped working with Catalina. I guess it has something to do with security permissions?

**Comment by DivineDominion** [comment]
Does any of you have trouble with the latest version when you _build it from source_, or only the binary download? 

I don't have Catalina installed, but since Catalina has tightened some security screws, it might be that building from source solves a couple of problems already because the app is then trusted.

**Comment by neutrinoceros** [comment]
I just want to report that the latest Catalina patch 10.15.2 solved this issue for me. So really it's just relevant for 10.15.0 and 10.15.1

**Comment by kkoomen** [comment]
> I just want to report that the latest Catalina patch 10.15.2 solved this issue for me. So really it's just relevant for 10.15.0 and 10.15.1

@neutrinoceros So you're saying that this script works again on 10.15.2 ?

**Comment by neutrinoceros** [comment]
Yes

**Comment by mhvuze** [comment]
It's truly bizarre: I decided to give this another go and built it from source. I provided one of the samples from the readme as arguments for running and Xcode. Low and behold, Catalina showed me the notification permission dialogue – after giving permission, it worked!

However: It only works for the binary in the build path. If I try to copy it to another location, it won't trigger the notification. Truly bizarre. I'll see how to make Xcode build to a directory of my choice, so I can properly use it. But hope it helps.

**Comment by riccardocossu** [comment]
I had to rebuild it on my machine, selecting "Sign for local use" and it works now.

**Comment by kkoomen** [comment]
I'm getting annoyed that @vjeantet is ignoring this issue completely.

@vjeantet Can you please support Cataline? You provided an open source program and people are waiting for this to be fixed.

**Comment by DivineDominion** [comment]
@kkoomen That's not how freely sharing your open source endeavors work :) You can build and run the software just fine from your local computer. Maybe you find someone who can build the binary for you if needed.

**Comment by vjeantet** [comment]
Hello all,

I’ll try to rebuild a binary tonight, and share results here.

**Comment by vjeantet** [comment]
new binary compiled available here : https://github.com/vjeantet/alerter/releases/tag/003

Anybody to confirm that it now works   ?

**Comment by riccardocossu** [comment]
I get "unidentified developer" error and it complains it can't be checked for malware

**Comment by riccardocossu** [comment]
a workaround is to download it through terminal:

`wget https://github.com/vjeantet/alerter/releases/download/003/alerter_v003_darwin_amd64.zip
unzip alerter_v003_darwin_amd64.zip `

**Comment by vjeantet** [comment]
Strange... Anybody know how I should build/sign the app to get rid of this message?

**Comment by riccardocossu** [comment]
I think you will have to pay Apple on a yearly basis to get a valid certificate; but I'm ok with using one of the workaround (build it myself or download through the terminal), after all it's a tool for advanced users

**Comment by MAJ007** [comment]
@vjeantet In addition to an Apple Dev ID which costs $99 which can be used to sign your app. You would also need to Notarise your app, which is now part of the build process - https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution

**Comment by MAJ007** [comment]
I would be more than happy to donate $ if you sign and notarise the app :)

**Comment by vjeantet** [comment]
99$... each year !  i'll think about it.

**Comment by MAJ007** [comment]
I would be more than Happy to contribute :)

**Comment by vjeantet** [comment]
Thanks @MAJ007 !

I set a support this project button in the README.MD, to allow financial contributions.
Goal : reach a sufficient amount of money to get an apple Developer ID. This will permit to sign and notarize alerter.
