### ISSUE TITLE
V3 - Doesn't work in macOS Big Sur

### ISSUE THREAD

**Issue by Sergey-Galan** [vjeantet/alerter#30]
V3 - Doesn't work in macOS Big Sur
While it is test system, but it is worth reflecting.

**Comment by vjeantet** [comment]
Hi I’m waiting for the final release of bigSur, to investigate.

**Comment by kishensurajp** [comment]
any update?

**Comment by Sergey-Galan** [comment]
> any update?

In release everything is good.

**Comment by danielamar101** [comment]
I have also come across the same issue in the official release of alerter.

**Comment by vjeantet** [comment]
Hello, a compiled version with BigSur is available in release : https://github.com/vjeantet/alerter/releases/tag/004
