### ISSUE TITLE
Bigsur support

### ISSUE THREAD

**Issue by That-Dude** [vjeantet/alerter#33]
I'm trying the latest binary from GitHub on Bigsur 11.0.1 and it seems to hang on the terminal until I press ctrl+c - no message displayed. Anything I can do?

**Comment by danielamar101** [comment]
I have also come across the same issue on MAcOS Big Sur.

**Comment by vjeantet** [comment]
Hello, a compiled version with BigSur is available in release : https://github.com/vjeantet/alerter/releases/tag/004.

Can you confirm that it works well now ?

**Comment by That-Dude** [comment]
> Hello, a compiled version with BigSur is available in release : https://github.com/vjeantet/alerter/releases/tag/004.
> 
> Can you confirm that it works well now ?

Still not working for me, sits at the terminal until I press CTRL+C

`./alerter -message "test message"`

 I had to manually allow it to run in security settings as expected, but it doesn't requires permission to use notifications - which I would have expected.
