### ISSUE TITLE
What do the -open, -execute and -activate options do ?

### ISSUE THREAD

**Issue by section83** [vjeantet/alerter#37]
The readme info on _Alerter _ says:

> Because of this it is important to note that you cannot combine this with options like -execute , -open , and -activate which depend on the sender of the notification to be ‘alerter’ to perform its work.

But, I can't find any detail on what -execute , -open , and -activate do.  I've played with adding them to my Alerter call (e.g. -open "/System/Applications/TextEdit.app").  but nothing happens.

I can't find any reference to them in the code so, are they planned for the future ?

Thanks.

**Comment by amandamana** [comment]
I think this is documentation mistake. Possible an artifact of merging and diverging or sharing parts of julienXX/terminal-notifier where these flags are valid.

**Comment by section83** [comment]
Yes, that seems correct.
