### ISSUE TITLE
"alerter" can't be opened because Apple cannot check it for malicious software

### ISSUE THREAD

**Issue by mottertektura** [vjeantet/alerter#42]
Hi, I'm running into an issue with alerter on 11.4 clients perhaps because the app is not notarized? I've tried packaging it using Composer and signing the installer package with a Developer ID certificate but when it's run I get the prompt "alerter" can't be opened because Apple cannot check it for malicious software.

<img width="372" alt="Screen Shot 2021-07-14 at 6 38 47 PM" src="https://user-images.githubusercontent.com/33263984/125704413-25fcc77b-1e33-4d68-84c2-ed39a8b7e371.png">

**Comment by section83** [comment]
I don't get any errors in macOS 10.15.7.  You could try building _Alerter_ yourself using _Xcode_. You can specify the signing etc.

**Comment by hybras** [comment]
Downloaded binaries frequently run into such problems. If you trust alerter, you can [bypass this](https://support.apple.com/en-us/HT202491) by "option + click" (this should open a shell and run the program, display help, then exit)

**Comment by mottertektura** [comment]
> Downloaded binaries frequently run into such problems. If you trust alerter, you can [bypass this](https://support.apple.com/en-us/HT202491) by "option + click" (this should open a shell and run the program, display help, then exit)
> 
> I'm not the dev, but I think u should close this issue.

I'm deploying with Jamf, so the "option + click" solution does not work for me. I've added a postinstall script to run the following command: 

xattr -dr com.apple.quarantine "/path/to/alerter"

That seems to work for now in case anyone is also looking for a solution. I will close the issue, but It think the real resolution would be notarization and signed package.

**Comment by section83** [comment]
Another option is to build a copy of _Alerter_ and sign it with your own Developer ID. You can then package it with your other components.
