### ISSUE TITLE
Option to remove "Close" & "Show" buttons 

### ISSUE THREAD

**Issue by moshed** [vjeantet/alerter#7]
is it possible to have the option to remove these buttons. the only option i see are to change the labels.
the original project https://github.com/julienXX/terminal-notifier defaults to this if you activate a simple `terminal-notifier -message "test"` but adding more things causes the buttons to show

**Comment by vjeantet** [comment]
Hello, I do not commit more on this repo, @JulienXX merged this repo, into terminal-notifier.

Can you elaborate on why do you still use/prefer alerter ? It will help Julien to improve its app or convince me to continue to maintain alerter

**Comment by moshed** [comment]
i just discovered this today but from what ive seen your fork is a simple script while his .app and his doesnt allow you to use a url as `-contentImage=<value>`

**Comment by julienXX** [comment]
@moshed terminal-notifier accepts URL as contentImage value (only https but http support is coming soon).

**Comment by moshed** [comment]
oh i think that was the issue. but either way i prefer your fork because it allows me to have just the script and not the whole .app bundle

**Comment by moshed** [comment]
thanks!
